name: Stage on new or updated pull request

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rust-code-format:
    name: Check rust code format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - run: cargo fmt -p bluepaper_core bluepaper bluepaper-wasm -- --check

  test-and-stage:
    name: Test, build, and stage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache backend (cargo) dependencies
      uses: actions/cache@v2
      with:
        path: |
          target
          .cargo_home
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Run backend tests
      run: CARGO_HOME=.cargo_home cargo test

    - name: Install wasm-pack 0.8.1
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Restrict to version 0.8.1 to work around this issue:
        # https://users.rust-lang.org/t/unexpected-wasm-opt-crash-when-running-wasm-pack/46573
        # https://github.com/rustwasm/wasm-pack/issues/886
        version: v0.8.1

    - name: Install node.js version 10.16 
      uses: actions/setup-node@v1
      with:
        node-version: 10.16

    - name: Audit npm dependencies (with --audit-level=high)
      run: cd wasm && npm audit --audit-level=high

    - name: Cache frontend (npm) dependencies
      uses: actions/cache@v2
      with:
        path: wasm/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('wasm/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install frontend (npm) dependencies
      run: cd wasm && npm install

    - name: Build app in release mode
      run: cd wasm && CARGO_HOME=../.cargo_home npm run build

    - name: Stage on gh-pages-staging
      id: staging
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./wasm/dist
        publish_branch: gh-pages-staging
        commit_message: Stage
